---
name: Other
description: Any issue that is not a feature or bug
labels: ["type: other", "status: needs triage"]
title: "[Other]: "
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: More Information
      description: What exactly are you opening this issue for?
    validations:
      required: true
